# Generated by Django 5.1.1 on 2025-01-25 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('New Patient', 'New Patient'), ('Follow-Up Patient', 'Follow-Up Patient'), ('Emergency Patient', 'Emergency Patient'), ('Preventive Care Patient', 'Preventive Care Patient')], max_length=30, null=True)),
                ('Problem', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Oral', 'Oral'), ('Topical', 'Topical'), ('Injectable', 'Injectable'), ('Inhalable', 'Inhalable'), ('Transdermal', 'Transdermal')], max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('Medicine_quantity', models.PositiveBigIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
            options={
                'verbose_name_plural': 'Medicine',
            },
        ),
    ]
