# Generated by Django 5.1.1 on 2025-01-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_patient_address_patient_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='category',
            new_name='medicine_category',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Medicine_quantity',
            new_name='medicine_quantity',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Problem',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
