# Generated by Django 5.1.1 on 2025-01-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_medicine_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
